package Fighters.Heros;

import java.util.*;
import Fighters.Attribute;
import Fighters.Fighter;
import Fighters.Stats;
import Structure.Inventory;
import Items.*;
import Locations.Marketplace;

public abstract class Hero extends Fighter {
  private Inventory inventory;
  private int goldAmount;
  private int experience;

  private Map<EquipmentSlot, Equippable> equipment;

  public Hero(String name, Stats stats, int startingMoney, int startingExperience) {
    super(name, 1, stats); // set level to 1
    inventory = new Inventory();
    goldAmount = startingMoney;
    experience = startingExperience;
  }

  // --------------------- battle related section
  @Override
  public void attack(Fighter target) {
    // TODO: autogenerated method stub
    Weapon left = (Weapon) equipment.get(EquipmentSlot.LEFT_HAND);
    Weapon right = (Weapon) equipment.get(EquipmentSlot.RIGHT_HAND);

    double damageDone = 0;
    if (left != null && left == right && left.getHasTwoHandedBonus()) {
      damageDone = left.getWeaponDamage() * 1.5;
    } else if (left != null && left == right && !left.getHasTwoHandedBonus()) {
      damageDone = left.getWeaponDamage();
    } else {
      damageDone = 0;
    }
    target.takeDamage((int) damageDone);
  }

  /**
   * sees if a target dodged or not based on their agility and other stats
   * 
   * @return true if dodged and false otherwise
   */
  public boolean didDodge() {
    double dodgeThreshold = stats.get(Attribute.AGILITY) * 0.002; // random must be under this value for dodge to be
                                                                  // successful
    double dodgeChance = generator.nextDouble();
    return dodgeChance <= dodgeThreshold;
  }

  /**
   * add the input amount of experience to a heroe's total
   * 
   * @param addedExperience
   */
  public void incrementExperience(int addedExperience) {
    experience += addedExperience;
    // continue leveling up multiple times at once iff possible
    while (levelUpIfPossible()) {
    }
  }

  /**
   * level up if possible
   * 
   * @return true if possible and false otherwise
   */
  public boolean levelUpIfPossible() {
    // return false if not enough experience to level up
    if (experience < level * 10) {
      return false;
    }
    level++;
    // all skills increase by 5% and favored skills increase by an extra 5%
    stats.levelUp();
    hp = level * 100;
    return true;
  }

  // --------------------- getters and setters
  /**
   * 
   * @return hero's gold amount
   */
  public int getGoldAmount() {
    return goldAmount;
  }

  /**
   * set new gold amounts
   * 
   * @param newGoldAmount
   */
  public void setGoldAmount(int newGoldAmount) {
    goldAmount = newGoldAmount;
  }

  public Stats getHeroStats() {
    return stats;
  }

  /**
   * populates the stats variable during its initialization before object is
   * created
   * 
   * @param stats
   * @param strength
   * @param dexterity
   * @param agility
   * @param mana
   * @return a populated stats variable
   */
  public static Stats populateStats(Stats stats, int strength, int dexterity, int agility, int mana) {
    stats.set(Attribute.STRENGTH, strength);
    stats.set(Attribute.DEXTERITY, dexterity);
    stats.set(Attribute.AGILITY, agility);
    stats.set(Attribute.MANA, mana);
    return stats;
  }

  /**
   * 
   * @return hero's inventory for updating by marketplace
   */
  public Inventory getInventory() {
    return inventory;
  }

  /**
   * @return true if equips successfully
   */
  public boolean equipItem(Equippable item, boolean useTwoHands) {
    if (item instanceof Weapon weapon) {
      // 2 handed weapon or 1 handed choosing to use 2 hands
      if (weapon.getRequiredHands() == 2 || (useTwoHands && weapon.getHasTwoHandedBonus())) {
        if (equipment.containsKey(EquipmentSlot.LEFT_HAND) ||
            equipment.containsKey(EquipmentSlot.RIGHT_HAND)) {
          return false;
        }
        equipment.put(EquipmentSlot.LEFT_HAND, weapon);
        equipment.put(EquipmentSlot.RIGHT_HAND, weapon);
      } else {
        // 1 handed weapon decide which hand
        if (!equipment.containsKey(EquipmentSlot.LEFT_HAND)) {
          equipment.put(EquipmentSlot.LEFT_HAND, weapon);
        } else if (!equipment.containsKey(EquipmentSlot.RIGHT_HAND)) {
          equipment.put(EquipmentSlot.RIGHT_HAND, weapon);
        } else {
          return false; // both hands full
        }
      }
      // armor
    } else if (item instanceof Armor armor) {
      if (!equipment.containsKey(EquipmentSlot.ARMOR)) {
        equipment.put(EquipmentSlot.ARMOR, armor);
      } else {
        return false;
      }
    }
    item.setIsEquipped(true);
    return true;
  }

  /**
   * 
   * @param item
   * @return true if unequips successfully
   */
  public boolean unequipItem(Equippable item) {
    boolean found = false;
    for (EquipmentSlot slot : EquipmentSlot.values()) {
      Equippable equipped = equipment.get(slot);
      if (equipped != null && equipped.equals(item)) {
        equipment.remove(slot);
        found = true;
      }
    }
    if (found) {
      item.setIsEquipped(false);
    }
    return found;
  }

  public String toString() {
    StringBuilder sb = new StringBuilder(name + " [LVL: " + level + "] [GLD: " + goldAmount + "]");
    // add the equipped items
    if (equipment != null) {
      if (equipment.get(EquipmentSlot.LEFT_HAND) != null) {
        sb.append("[HL: " + equipment.get(EquipmentSlot.LEFT_HAND) + "]");
      }
      if (equipment.get(EquipmentSlot.ARMOR) != null
          && equipment.get(EquipmentSlot.LEFT_HAND) == equipment.get(EquipmentSlot.RIGHT_HAND)) {
        sb.append("[HR: " + equipment.get(EquipmentSlot.RIGHT_HAND) + "]");
      }
      if (equipment.get(EquipmentSlot.ARMOR) != null) {
        sb.append("[ARMOR: " + equipment.get(EquipmentSlot.ARMOR) + "]");
      }
    }
    return sb.toString();
  }
}
