@startuml LegendsMonstersHeroesNoUsageRelationships
skinparam classBackgroundColor #FEFEFE
skinparam classBorderColor #000000
skinparam arrowColor #000000

' ================== INTERFACES ==================
interface Copyable<T> {
  +{abstract}T copy()
  +{abstract}int getLevel()
}

interface Consumable {
  +{abstract}boolean consumeItem(Hero h)
}

interface AttackWith {
  +{abstract}int getDamage()
}

' ================== ABSTRACT CLASSES ==================
abstract class Fighter {
  #{field}Random generator
  #{field}String name
  #{field}int level
  #{field}int hp
  #{field}Stats stats
  
  +Fighter(String name, int level, Stats stats)
  +{abstract}void attack(Fighter target)
  +int takeDamage(int damage)
  +int getFighterHp()
  +void setFighterHp(int newHp)
  +{abstract}boolean didDodge()
  +boolean isAwake()
  +String getName()
  +int getLevel()
  +String toString()
}

abstract class Hero extends Fighter implements Copyable<Hero> {
  -Inventory inventory
  #int goldAmount
  #int experience
  -Weapon attackWeapon
  -Map<EquipmentSlot,Equippable> equipment
  
  +Hero(String name, Stats stats, int startingMoney, int startingExperience)
  +void attack(Fighter target, Item weapon)
  +void attack(Fighter target)
  +boolean useSpell(Spell sp, Fighter target)
  +boolean didDodge()
  +int takeDamage(int damage)
  +void incrementExperience(int addedExperience)
  +boolean levelUpIfPossible()
  +int getGoldAmount()
  +void setGoldAmount(int newGoldAmount)
  +Stats getHeroStats()
  +{static}Stats populateStats(Stats stats, int strength, int dexterity, int agility, int mana)
  +Inventory getInventory()
  +boolean equipItem(Equippable item, boolean useTwoHands)
  +boolean unequipItem(Equippable item)
  +boolean loopToManageInventory(IO io)
  +int manageInventory(IO io)
  +String toLongString()
  +String toLongStringWithInventory()
  +String inventoryToList()
}

abstract class Monster extends Fighter implements Copyable<Monster> {
  +Monster(String name, int level, Stats stats)
  +boolean didDodge()
  +void attack(Fighter target)
  +{static}Stats populateStats(Stats stats, int baseDamage, int increasedDefense, int agility)
  +String toString()
}

abstract class Item implements Copyable<Item> {
  #{field}String name
  #{field}int cost
  #{field}int requiredLevel
  
  +Item(String nameInput, int costInput, int requiredLevelInput)
  +String getName()
  +int getCost()
  +void setCost(int newCost)
  +int getRequiredLevel()
  +String getNameAndLevel()
  +String toString()
}

abstract class Equippable extends Item {
  +{static}final int MAX_DURABILITY
  #boolean isEquipped
  #int durability
  #boolean isBroken
  
  +Equippable(String nameInput, int costInput, int requiredLevelInput)
  +boolean getIsEquipped()
  +void setIsEquipped(boolean isEquippedNow)
  +int getDurability()
  +void setDurability(int newDurability)
  +boolean isDurable()
  +boolean isBroken()
  +boolean reduceDurability()
  +String toString()
}

abstract class Space {
  -int row
  -int col
  
  +Space(int r, int c)
  +{abstract}String getSpaceType()
  +String debugSpace()
}

' ================== CONCRETE CLASSES ==================
class Warrior extends Hero {
  +Warrior(String name, int mana, int strength, int agility, int dexterity, int startingMoney, int startingExperience)
  +{static}Stats createStats(int strength, int dexterity, int agility, int mana)
  +Warrior copy()
}

class Sorcerer extends Hero {
  +Sorcerer(String name, int mana, int strength, int agility, int dexterity, int startingMoney, int startingExperience)
  +{static}Stats createStats(int strength, int dexterity, int agility, int mana)
  +Sorcerer copy()
}

class Paladin extends Hero {
  +Paladin(String name, int mana, int strength, int agility, int dexterity, int startingMoney, int startingExperience)
  +{static}Stats createStats(int strength, int dexterity, int agility, int mana)
  +Paladin copy()
}

class Dragon extends Monster {
  +Dragon(String name, int level, int baseDamage, int increasedDefense, int agility)
  -{static}Stats createStats(int baseDamage, int increasedDefense, int agility)
  +Dragon copy()
}

class Spirit extends Monster {
  +Spirit(String name, int level, int baseDamage, int increasedDefense, int agility)
  -{static}Stats createStats(int baseDamage, int increasedDefense, int agility)
  +Spirit copy()
}

class Exoskeleton extends Monster {
  +Exoskeleton(String name, int level, int baseDamage, int increasedDefense, int agility)
  -{static}Stats createStats(int baseDamage, int increasedDefense, int agility)
  +Exoskeleton copy()
}

class Weapon extends Equippable implements AttackWith {
  -int baseDamage
  -int requiredHands
  -boolean isTwoHanded
  
  +Weapon(String name, int cost, int level, int damage, int requiredHands)
  +void setIsEquipped(boolean isEquippedNow)
  +int getRequiredHands()
  +boolean canUseTwoHands()
  +boolean isTwoHanded()
  +void setTwoHanded(boolean twoHanded)
  +int getDamage()
  +double getDamageMultiplier()
  +boolean useWeapon()
  +List<EquipmentSlot> getEquipmentSlotOptions()
  +Weapon copy()
  +int getLevel()
  +String toString()
}

class Armor extends Equippable {
  -int baseDefense
  
  +Armor(String name, int cost, int level, int defense)
  +int getBaseDefense()
  +Armor copy()
  +int getLevel()
  +String toString()
}

class Spell extends Item implements Consumable, AttackWith {
  -int damage
  -int manaCost
  
  +Spell(String nameInput, int costInput, int requiredLevelInput, int damageInput, int manaCostInput)
  +int getDamage()
  +boolean consumeItem(Hero h)
  +Spell copy()
  +int getLevel()
}

class Potion extends Item implements Consumable {
  -int attributeIncrease
  -List<Object> attributesAffected
  -String attributesAffectedString
  
  +Potion(String nameInput, int costInput, int requiredLevelInput, int attributeIncreaseInput, String attributesAffectedStringInput)
  +boolean consumeItem(Hero h)
  +Potion copy()
  +int getLevel()
}

class Stats {
  -EnumMap<Attribute,Integer> attributes
  -Set<Attribute> favoredAttributes
  
  +Stats(Set<Attribute> favoredAttributes)
  +void set(Attribute attr, int value)
  +int get(Attribute attr)
  +void levelUp()
}

class Inventory extends ArrayList<Item> {
  +Item getItemByName(String name)
  +Inventory filterByItemClass(Class<? extends Item> type)
  +Inventory filterByEquipped()
  +String toString()
}

class Board {
  -int NUM_BOARD_ROWS
  -int NUM_BOARD_COLS
  -Space[][] board
  -Random generator
  -int playerRow
  -int playerCol
  
  +Board()
  +boolean isValidMove(String direction)
  +boolean canMoveToSpace(int r, int c)
  -boolean indexIsOnBoard(int boardIndex)
  +void setPlayerBoardPosition(int r, int c)
  +Space getCurrentSpace()
  +String getCurrentSpaceType()
  +String toString()
  +String spaceToString(int r, int c)
}

class CommonSpace extends Space {
  -Random generator
  -boolean isBattleHere
  -boolean monstersDefeated
  
  +CommonSpace(int r, int c)
  +String getSpaceType()
  +boolean getIsBattleHere()
  +boolean getHaveMonstersBeenDefeated()
  +void setMonstersDefeated(boolean monstersDefeated)
  +String toString()
}

class MarketSpace extends Space {
  -Marketplace marketplace
  
  +MarketSpace(int r, int c)
  +String getSpaceType()
  +String toString()
  +Marketplace getMarketplace()
}

class StartingSpace extends Space {
  +StartingSpace(int r, int c)
  +String getSpaceType()
  +String toString()
}

class InaccessibleSpace extends Space {
  +InaccessibleSpace(int m, int n)
  +String getSpaceType()
  +String toString()
}

class Game {
  -Board board
  -Scanner scan
  -IO io
  -String playerName
  -int partySize
  -List<Hero> party
  
  +void start()
  +void gameSetup()
  +void playGame()
  -void addHeroesToParty(int partySize)
}

class Battle {
  -List<Hero> heroes
  -List<Hero> awakeHeroes
  -List<Monster> monsters
  -List<Monster> awakeMonsters
  -IO io
  -Random generator
  
  +Battle(List<Hero> input_hero_list, IO io)
  +boolean playBattle()
  +boolean playSingleRound()
  +boolean heroPlaysMove(Hero h)
  -void checkHpAndPrintIfFainted(Fighter f)
  -void monsterPlaysMove(Monster m)
  -void showstatsAction()
  -void rewardHeroesForWinningBattle()
}

class Marketplace {
  -Inventory inventory
  -Random generator
  -IO io
  
  +Marketplace()
  -void stockInventory()
  +boolean enter(Hero h)
  +int doTurnAtMarket(Hero h)
  -void transactWithHeroLoop(Hero h, List<? extends Object> goodsToExchange, Function<Integer,Boolean> transactWithHero)
  -boolean sellItemToHero(Hero h, int index)
  -boolean buyItemFromHero(Hero h, int index)
  -boolean repairItemForHero(Hero h, int index)
}

class IO {
  +{static}final String validMoveOptions
  +{static}final String nextMoveListWithMarket
  +{static}final String nextMoveListWithoutMarket
  -Scanner sc
  
  +IO(Scanner scan)
  +String getNextMove(boolean isOnMarketSpace)
  +String getPlayerName()
  +int getPartySize()
  +String getHeroType()
  +int getValidListIndex(List<? extends Object> inputList, boolean canGoBack, String itemsType)
  +Object[] getListIndexorEquippingOptionForManagingInventory(Hero h)
  +String getMarketAction()
  +String getHeroBattleAction(Hero h)
  +void printGameIntro(String playerName)
  +{static}void printListWithIndices(List<? extends Object> inputList)
  +void printHelpMenu()
}

class Main {
  +{static}void main(String[] args)
}

class RandomFactory<T extends Copyable<T>> {
  -List<T> templates
  -Random rand
  
  +RandomFactory(List<T> templates)
  +T random()
}

class MonsterLevelFactory<T extends Monster> {
  -Map<Integer,List<T>> byLevel
  -Random rand
  
  +MonsterLevelFactory(List<T> monsters)
  +Monster random(int level)
}

class DataLoader {
  +{static}<T> List<T> load(String path, Function<String[],T> builder)
}

class GameData {
  +{static}RandomFactory<Warrior> warriors
  +{static}RandomFactory<Sorcerer> sorcerers
  +{static}RandomFactory<Paladin> paladins
  +{static}MonsterLevelFactory<Monster> monsters
  +{static}RandomFactory<Item> items
  
  +{static}void loadAll()
  -{static}void loadHeroes()
  -{static}void loadMonsters()
  -{static}void loadItems()
}

enum Attribute {
  MANA
  STRENGTH
  DEXTERITY
  AGILITY
  DEFENSE
  DAMAGE
}

enum EquipmentSlot {
  LEFT_HAND
  RIGHT_HAND
  ARMOR
}

' ================== RELATIONSHIPS ==================
' Inheritance relationships
Fighter <|-- Hero
Fighter <|-- Monster
Hero <|-- Warrior
Hero <|-- Sorcerer
Hero <|-- Paladin
Monster <|-- Dragon
Monster <|-- Spirit
Monster <|-- Exoskeleton
Item <|-- Equippable
Equippable <|-- Weapon
Equippable <|-- Armor
Item <|-- Spell
Item <|-- Potion
Space <|-- CommonSpace
Space <|-- MarketSpace
Space <|-- StartingSpace
Space <|-- InaccessibleSpace

' Interface implementations
Copyable <|.. Fighter
Copyable <|.. Hero
Copyable <|.. Monster
Copyable <|.. Item
Consumable <|.. Spell
Consumable <|.. Potion
AttackWith <|.. Weapon
AttackWith <|.. Spell

@enduml
